Fix Packell CI: load Nix profile before nix-shell

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -339,6 +339,16 @@ jobs:
       - run:
           name: Build Packell
           command: |
+            echo "Loading Nix environment..."
+            if [ -f /home/circleci/.nix-profile/etc/profile.d/nix.sh ]; then
+              . /home/circleci/.nix-profile/etc/profile.d/nix.sh
+            elif [ -f ~/.nix-profile/etc/profile.d/nix.sh ]; then
+              . ~/.nix-profile/etc/profile.d/nix.sh
+            else
+              echo "Nix profile not found!"
+              exit 1
+            fi
+
             nix-shell tools/packell/default.nix --run 'echo "Done building Packell."'
             cp /nix/store/*packell*/bin/packell .
       - store_artifacts:
