install nix on CI

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -283,6 +283,9 @@ jobs:
 
             if [ -f /home/circleci/.nix-profile/etc/profile.d/nix.sh ]; then
               source /home/circleci/.nix-profile/etc/profile.d/nix.sh
+            else
+              echo "ERROR: Nix not found!"
+              exit 1
             fi
 
             source $BASH_ENV
