CI Build Packell - fix nix

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -356,14 +356,20 @@ jobs:
           name: Build Packell
           command: |
             echo "Loading Nix environment..."
-            source "$BASH_ENV"
+
+            if [ -f /home/circleci/.nix-profile/etc/profile.d/nix.sh ]; then
+              . /home/circleci/.nix-profile/etc/profile.d/nix.sh
+            elif [ -f ~/.nix-profile/etc/profile.d/nix.sh ]; then
+              . ~/.nix-profile/etc/profile.d/nix.sh
+            else
+              echo "Nix not found!"
+              exit 1
+            fi
 
             nix-shell tools/packell/default.nix --run 'echo "Done building Packell."'
-
-            mkdir -p packell-linux
-            cp /nix/store/*packell*/bin/packell packell-linux/packell
+            cp /nix/store/*packell*/bin/packell .
       - store_artifacts:
-          path: packell-linux
+          path: packell
 
 workflows:
   version: 2
